debug: false

logging:
  path: ./log


spring:
  datasource:
#    url: jdbc:mysql://47.101.164.238:3306/elab?characterEncoding=utf-8&useSSL=false
#    username: root
#    password:
    url: jdbc:mysql://172.19.189.117:3306/elab?characterEncoding=utf-8&useSSL=false
    username: root
    password: Elab@2018
#    url: jdbc:mysql://106.14.225.13:3306/elab?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: Elab@2018

  jackson:
    serialization:
      fail_on_empty_beans: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port : 8081


