debug: false

logging:
  path: /Users/mawic/Downloads/log


spring:
  datasource:
    url: jdbc:mysql://47.101.164.238:3306/elab?characterEncoding=utf-8&useSSL=false
    username: root
    password:

  jackson:
    serialization:
      fail_on_empty_beans: false
